# Generated by Django 4.0.1 on 2022-03-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaflix', '0002_alter_category_options_remove_actor_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='actor',
            name='sex',
            field=models.CharField(choices=[['male', 'Muž'], ['female', 'Žena'], ['other', 'Ostatní']], default='male', max_length=32),
        ),
    ]
